# Generated by Django 6.0.3 on 2026-03-06 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crawl_playlist", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Video_List",
            new_name="VideoList",
        ),
    ]
